camera: 
    resolution: 
        - 320
        - 240
    framerate: 30
    image_effect: "denoise"
    exposure_mode: "fixedfps"
    awb_mode: "off"
    awb_gains:
        - 1.3
        - 2.4
vision:
    fov:
        - 1.085595
        - 0.8517207
    camTilt: 1.20
    camHeight: 0.08
    dribblerMult: 0.85
    properties:   
        ball:
            dimensions:
                - 0.0427
                - 0.0427
        obstacle: 
            dimensions: 
                - 0.18 
                - 0.225
        goal: 
            dimensions: 
                - 0.7
                - 0.225

    thresholds: 
        ball:
            lower: 
                - 0
                - 100
                - 150
            upper: 
                - 15
                - 255
                - 255
            kernel: 3
        grass:
            lower:
                - 40
                - 30
                - 25
            upper:
                - 60
                - 255
                - 255
            kernel: 9
        wall:
            lower: 
                - 0
                - 0
                - 100
            upper: 
                - 255
                - 50
                - 255
            kernel: 9
        yellowGoal:
            lower: 
                - 22
                - 100
                - 110
            upper: 
                - 33
                - 255
                - 255
            kernel: 9
        blueGoal:
            lower:
                - 95
                - 128
                - 63
            upper:
                - 110
                - 255
                - 255
            kernel: 9
        obstacle: 
            lower:
                - 0
                - 0
                - 0
            upper: 
                - 30
                - 255
                - 25
            kernel: 9
drive:
    wheelHz: 4.6
    wheelDiameter: 0.067
    wheelR: 0.09
    wheelPins:
        -
            fwd: 1
            rev: 2
        -
            fwd: 15
            rev: 14
        -
            fwd: 13
            rev: 12
    dribblerPins:
        fwd: 3
        rev: 4
ai:
    initHeading: 0
    ballSearchMoveCount: 3
    ballSearchSpinCount: 10
    goalSearchMoveCount: 3
    goalSearchSpinCount: 10
    virtballturncount: 3
    forwardVelocity: 0.5
    rotationalVelocity: 0.2
    distToGrab: 0.01
    objWidth: 0.15